### ISSUE TITLE
Feature: assets folder as option in theme.json

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#1]
It would be nice if the folder that's used to publish in laravel's `public/` folder is configurable in the `theme.json` file. 

Like for instance:

``` json
{
  "name": "Demo",
  "description": "This is a demonstration theme",
  "dist": "assets"
}

```

This way we can customize what's being published. And also so the less/sass files aren't getting published in the public folder.

**Comment by kirkbushell** [comment]
Will add this shortly, as it's been on my mind :)

**Comment by nWidart** [comment]
Awesome :+1:

**Comment by kirkbushell** [comment]
Gonna get onto this today mate - and try and fix the damn build suite. lol

**Comment by nWidart** [comment]
Nice! Indeed that travis build would be great.
