### ISSUE TITLE
Theme inheritance

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#12]
Hello,

I tried the theme inheritance today. Like it's stated in the documentation, by adding a`"parent": "AdminLTE"` key in the `theme.json` file.
This is the structure:

```
Themes
  |- AdminLTE
      |- TrendsShopAdmin
```

Though, it tries to load the assets in the new theme folder (`TrendsShopAdmin`).
I thought it would maybe first look in that folder but, if not found, it'd fall back to the parent theme (`AdminLTE`). 
Maybe that's what you said about inheritance a while back though, and it's working as intended, not sure.

Thanks,

**Comment by kirkbushell** [comment]
@nWidart is this still an issue?

**Comment by kirkbushell** [comment]
@nWidart

**Comment by nWidart** [comment]
Whoops forgot to reply on this one. Need to test it again.

**Comment by kirkbushell** [comment]
@nWidart closing, if still an issue please re-open.
