### ISSUE TITLE
Force module in theme::{script,style,url}

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#13]
Would it be possible to have a second argument to `Theme::script`, `Theme::style` and `Theme::url`, to pass a theme name.

``` php
Theme::script('script/url', 'ThemeName')
Theme::style('script/url', 'ThemeName')
Theme::url('script/url', 'ThemeName')
```

Thanks

**Comment by kirkbushell** [comment]
Could you explain the use-case and context?

**Comment by nWidart** [comment]
Well I maybe have an edge-case here. I have a view where styles and scripts are in another theme.
I went around this limitation by just using the `asset()` helper, and directly pointing to the theme I needed.

**Comment by kirkbushell** [comment]
That's really not how theming works. If it needs assets from other themes, you may want to think about either:

1. Extending that theme with the new one or
2. Copying those theme files across

**Comment by nWidart** [comment]
Yes you're right. I'll indeed copy those assets over. :)

About extending themes (#12), I can't seem to use the parent's assets in a child theme.


Thanks,

**Comment by kirkbushell** [comment]
Hmmm... should be generating both stylesheets. As for other assets, might be a bug there. hehe
