### ISSUE TITLE
Please tag 1.0

### ISSUE THREAD

**Issue by mvdstam** [floatingpointsoftware/stylist#15]
Please tag the latest commit as being 1.0. Forcing people to use `dev-master` is unnecessary and a bad practice.

**Comment by kirkbushell** [comment]
The repository is still a little unstable, as tests have been broken for a while. It looks like I've just resolved that now, so will look to push up a 0.1 release pretty soon.

**Comment by kirkbushell** [comment]
Version 0.1 has now been released.

**Comment by mvdstam** [comment]
Thanks! :smile:
