### ISSUE TITLE
Feature: Add argument to stylist:publish

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#2]
It might be nice to be able to send an argument to the `stylist:publish` which tells which theme to publish.

**Comment by kirkbushell** [comment]
What would be the benefit of that? Stylist requires a tree of inheritance so it's sort of a requirement for all registered themes to publish their assets.

**Comment by nWidart** [comment]
Hm I was thinking if there are multiple themes, maybe it's not always desirable to publish all. 

But not that I think of it, that'll probably never going to be the case.

**Comment by kirkbushell** [comment]
hehe - even if it wasn't desired, the only real loss/issue would be someone snooping around your assets directories.

**Comment by kirkbushell** [comment]
This has now been added.
