### ISSUE TITLE
Theme inheritence with JS

### ISSUE THREAD

**Issue by joshbrw** [floatingpointsoftware/stylist#22]
Any chance we could look in the parent theme for a JS file similar to how CSS works

**Comment by joshbrw** [comment]
Any updates on this? This is a massive blocker. It doesn't make sense that this works for CSS (barely) and not JS.

**Comment by kirkbushell** [comment]
Sure - feel free to setup a PR :)

**Comment by kirkbushell** [comment]
@joshbrw had a good think about this - could you explain the use-case more clearly? JS is usually business logic, not theme based.

**Comment by joshbrw** [comment]
@kirkbushell Exactly, so it makes sense for rendering the JS file loading to fall back to the Parent theme, as the child theme may only have small amendments to the styling of the theme but require the same JS functionality as the parent theme.

**Comment by kirkbushell** [comment]
My thinking is that the parent theme shouldn't be loading the JS from its theme directory - it should probably be from something like public/js/app

.etc.

**Comment by kirkbushell** [comment]
Also what issues were you having with the CSS theme inheritance? You said it barely works, so I'm interested to know what is wrong with it.

**Comment by joshbrw** [comment]
The CSS functionality is a bit strange, as i'd expect it to only load one version of the CSS file (sorry, this issue is a bit old, i solved it hard-referencing the theme i wanted to load the CSS from). Also, you can only have a single level of inheritance.

**Comment by kirkbushell** [comment]
@joshbrw not sure I follow. Do you mean you expected it to load one CSS file, with the parent's CSS included?

**Comment by joshbrw** [comment]
I expect it to go:

1. Does the current theme have the CSS file? If it does, reference that one and finish.
2. Loop through each parent theme, if it finds the file, reference that one and finish.
3. File not found in any parent? Throw exception

**Comment by kirkbushell** [comment]
@joshbrw the problem with that is the theme inheritance is designed to inherit/overload from parents. If I understand you correctly, you want only the child to load CSS, and not load subsequent parent CSS files.

**Comment by joshbrw** [comment]
I mean that only one version of the CSS file should be loaded, the version that is most relevant to the current theme, so if the current theme has that file it should load that one, if not then it should loop downwards through child themes until it finds it.

**Comment by kirkbushell** [comment]
@joshbrw that's the opposite of how the theme system is intended to work. With Stylist, children inherit, not parents. Technically, you're loading separate CSS files, not the same file but a different version. Perhaps "skin" is a better term here in regards to CSS - the idea is that the child is only loading CSS that is either in addition to, or overwrites - parent settings.

**Comment by kirkbushell** [comment]
@joshbrw as an additional point, the system was originally designed for CMS/blog type applications, where themes may be written by authors, and then subsequently modified by other authors by overloading certain assets (such as images, css.etc.).

**Comment by kirkbushell** [comment]
@joshbrw closing for now as I believe your intention is very different to how Stylist operates. If this is not the case, we can re-open.

**Comment by nWidart** [comment]
Oh : ( so we can't have theme inheritance. 

I chose to use this package at its early days because you said this was a feature coming soon. 😞

**Comment by nWidart** [comment]
> @joshbrw as an additional point, the system was originally designed for CMS/blog type applications, where themes may be written by authors, and then subsequently modified by other authors by overloading certain assets (such as images, css.etc.).

We use Stylist on AsgardCms, and we can't use theme inheritance because of this. However having a working theme inheritance would nice. Not only for views but also for all the assets (js/css/img).

**Comment by joshbrw** [comment]
+1 for asset inheritence. I'm having to manually reference the assets for the theme i need them from, even if that theme is my current themes parent.

**Comment by kirkbushell** [comment]
I think there's a misunderstanding here guys - theme inheritance DOES work (if it doesn't, please raise a separate issue), but it seems to me that the way you want it to work is different to how it does actually work. JS is the only aspect of it that will not inherit, because JS is generally business logic - not styling.

**Comment by kirkbushell** [comment]
@nWidart see comment above. Images do inherit like eg.views. - it should be looking in child themes first for images, then working up through the tree. CSS files are slightly different - it should load all parent CSS files, before loading the child ones. This provides an overloading-type mechanism for skinning themes.
