### ISSUE TITLE
can not activate theme

### ISSUE THREAD

**Issue by appdezign** [floatingpointsoftware/stylist#24]
Could you tell me how and where I have to activate the theme?
The docs show that I have to add:

```
Stylist::registerPath('/absolute/path/to/theme', true);
```

but I don't know where I have this add this line.
A little help would be greatly appreciated

**Comment by appdezign** [comment]
By the way: I'm using Laravel 5.1

**Comment by kirkbushell** [comment]
Hi there!

Usually you'd do this in a service provider, in the boot method. So for example, maybe you'd setup your own ThemeServiceProvider, and in the boot method you'd register the path to your theme. 

Please re-open if you have any further issues :)

**Comment by appdezign** [comment]
OK. For the time being I put it in the boot method of AppServiceProvider.
But that seems to work only with just one theme.
But when I try to define a parent theme, I get an exception:

    ThemeNotFoundException in Stylist.php line 186:
    Theme [default] is not registered with Stylist.

Now, I've tried to register both themes (using registerPath and registerPaths), but I can not get that to work. Can you tell me how to manually register two themes (parent/child) in a serviceProvider and then activate one (child)?

**Comment by kirkbushell** [comment]
First you must register the paths of the themes:

```php
Stylist::registerPath('/path/to/parent', true);
Stylist::registerPath('/path/to/child', true);
```

This shoudl allow you to do what you need.

The alternative is to allow Stylist to discover your themes if they all share a root directory (something like /themes), and then activate the one you wish to have active.

**Comment by appdezign** [comment]
I've already tried using registerPath twice, and I still get:

    Theme [default] is not registered with Stylist.

I'm pretty sure that I've got no typos. When I only register the child theme, I get the child view. And when I only register the parent view, I get the parent view. But when I register both, I get the exception. Really weird. Any ideas?

**Comment by kirkbushell** [comment]
You'll need to show some code at this point as I'm not sure what's going on. It's possible there's a bug in some weird instance.

**Comment by appdezign** [comment]
This what I've got. If you need more, then let me know.

Parent theme.json:

    {
    "name": "parent",
    "description": "Parent theme",
    }

Child theme.json

    {
    "name": "child",
    "description": "Child theme",
    "parent":  "parent"
    }

AppServiceProvider.php

    namespace App\Providers;

    use Illuminate\Support\ServiceProvider;
    use Stylist;

	class AppServiceProvider extends ServiceProvider
    {
        public function boot() {
    
            Stylist::registerPath(base_path('themes/parent'), true);
            Stylist::registerPath(base_path('themes/child'), true);
    
        }
    
    }

**Comment by kirkbushell** [comment]
Thanks for that. That all looks fine to me, though you don't need to activate the parent if you're not going to use it. Another way to do what you're doing is this:

```php
Stylist::registerPaths(base_path('themes/parent'), base_path('themes/child'));
Stylist::activate('child');
```

Will need a bit more if it still doesn't work after that. I'm not sure where it's getting default from.

**Comment by kirkbushell** [comment]
Ah, hang on - are you using the StylistServiceProvider? If so, you can configure the paths and themes there, and you won't need to do the custom registration work.

**Comment by appdezign** [comment]
I've tried your suggestion (registerPaths and activate) earlier today and I get an exception:

    ErrorException in Stylist.php line 106: Argument 1 passed to FloatingPoint\Stylist\Theme\Stylist::registerPaths() must be of the type array, string given, called in /home/vagrant/Code/lara-style/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 219 and defined

**Comment by kirkbushell** [comment]
You should be passing an array - apologies, my example before didn't do that.

**Comment by appdezign** [comment]
Of course, just fixed that, but I'm still getting an exception:

    ThemeNotFoundException in Stylist.php line 186: Theme [parent] is not registered with Stylist.

**Comment by appdezign** [comment]
By the way:
I had some other packages installed earlier, so just to be sure, I just installed a fresh copy of Laravel 5.1 on homestead and installed only two packages: Collective\Html and FloatingPoint\Stylist.
And I copied the themes folder (with parent en child subfolders) to the root. Same results.

**Comment by kirkbushell** [comment]
@appdezign okay, there must be an issue with theme registration somewhere. I'll do some investigation.

**Comment by kirkbushell** [comment]
@appdezign one of the tests in the test suite tests for exactly this behaviour, see: https://github.com/floatingpointsoftware/stylist/blob/master/tests/Theme/StylistTest.php#L52-L65

I'm not entirely sure what you're doing wrong, but the code appears to be working as you'd expect.

The only thing I can think of atm is that the paths you're passing in are incorrect.

**Comment by appdezign** [comment]
I found the problem. There was a comma at the end of the last line in the theme.json of the parent:

    {
    "name": "parent",
    "description": "Parent theme",
    }

That's why the parent theme never got registered.

**Comment by appdezign** [comment]
When I was debugging this, I did notice that there may be a problem in the boot method of your StylistServiceProvider. On line 51 it says:

    $paths = $this->app['config']->get('stylist.paths', []);

So it's trying to read \config\stylist.php, right?
But when I add my paths to this config file the paths are not read properly.
The array is always empty.
Shouldn't this be:

    $paths = $this->app['config']->get('stylist.themes.paths', []);

Because the contents of the config file are:

    return [
        'themes' => [
            'paths' => [
            ],
            'activate' => null
        ]
    ];

**Comment by appdezign** [comment]
But anyway, your package is working now (I'm not using the config file now), so thank you for your time

**Comment by kirkbushell** [comment]
Ah, good spot on the config - I'll fix that up :)

**Comment by dulabs** [comment]
I have fixed bootThemes with 
```PHP        
$stylist = $this->app['stylist'];
        $paths = $this->app['config']->get('stylist.themes.paths', []);

        foreach ($paths as $path) {
            $themePaths = $stylist->discover($path);
            $stylist->registerPaths($themePaths);
        }

        $theme = $this->app['config']->get('stylist.themes.activate', null);

        if (!is_null($theme)) {
            $stylist->activate($theme, true);
        }
```
