### ISSUE TITLE
No 0.3 Tag

### ISSUE THREAD

**Issue by joshbrw** [floatingpointsoftware/stylist#25]
Hi, could you please tag a 0.3 with the parent/child view loading so I can get the latest dependencies in my project? Don't want to use `dev-master` really.

This is the change: https://github.com/floatingpointsoftware/stylist/commit/c9d655a4fdac0d6b1718b3b141fe46f2fd9d1d9c

Thanks

**Comment by nWidart** [comment]
+1 :smile:

**Comment by kirkbushell** [comment]
Done.

**Comment by joshbrw** [comment]
Thanks a lot! :smile:
