### ISSUE TITLE
Views in queues are not picked up

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#26]
Hello,

When sending an email with a blade template inside a theme, the view is not getting picked up by laravel's view finder. 

When I added the view in the default namespace, `resources/` it was picked up.

**Comment by kirkbushell** [comment]
That's weird, as they should be using the same system...

**Comment by kirkbushell** [comment]
@nWidart any updates on this?

**Comment by joshbrw** [comment]
I believe this may have something to do with either the order of the Service Providers being loaded (as Laravel's `FileViewFinder` has paths added to it by Stylist), or down to Theme inheritance.

**Comment by nWidart** [comment]
I haven't tried it again since I've added the views to the `resource/` folder to avoid the issue. However if nothing was changed on the package I assume it's still here.

**Comment by kirkbushell** [comment]
I'll see if i can replicate in a test.

**Comment by nWidart** [comment]
I just had the same issue again. Same fix was to copy the view inside laravel's resource/views folder.

**Comment by kirkbushell** [comment]
I think I may have figured out what's going on here.

Basically, it appears as though the path finding in Laravel doesn't work as I suspected. the addLocation() does indeed add a new $path to the available paths, but the order in which it then looks for paths is completely backwards - it starts with those registered first, when it should be the other way around. I found this out by doing some other, related work on another project - it's just not loading paths as I want them to.

Long and short of it is that when I have a fix, I'll apply it here also @nWidart @joshbrw .

**Comment by kirkbushell** [comment]
@nWidart okay so finally got around to this - I wrote a new test that tests the loaded order. I think I need to look closer at what you're doing, as I'm unable to replicate. In short, the loader and the way laravel loads files for view paths appear to be accurate.
