### ISSUE TITLE
How to check if in current Theme i have a template view?

### ISSUE THREAD

**Issue by arturmamedov** [floatingpointsoftware/stylist#30]
I need to check if view file exist before tell to my controller how and what render.
I see stylist have a `view` property with `finder` and `paths` in this last i have the paths of my templates and here i need to do my check, but i can access a private property... there is another way?

If not, how the right way to contribute and create the method for doing this check.

Many thanks in advance!

**Comment by joshbrw** [comment]
You can do `app('view.finder')->find('viewname')`. It will throw a
`InvalidArgumentException` if it can't be found.

**Comment by arturmamedov** [comment]
Thank you very much! Its what i'm looking for, but not work correctly for me.

What if i have a path to? `backend.user.role.index`
And why in object `view.finder` i see only one path, the general laravel.
```
FileViewFinder {#553 ▼
  #files: Filesystem {#150}
  #paths: array:1 [▼
    0 => "D:\serverpath\B04-Aprile2016\PaluSoft\www\laravel\resources\views"
  ]
  #views: []
  #hints: []
  #extensions: array:2 [▼
    0 => "blade.php"
    1 => "php"
  ]
}
```

**Comment by joshbrw** [comment]
Ensure that your `StylistServiceProvider` is loading before the time you check the paths on the `FileViewFinder`, as Stylist adds new paths to the `FileViewFinder`:

https://github.com/floatingpointsoftware/stylist/blob/master/src/Stylist/StylistServiceProvider.php#L55
https://github.com/floatingpointsoftware/stylist/blob/master/src/Stylist/Theme/Stylist.php#L135

**Comment by arturmamedov** [comment]
Ok i check later today and let you know, many thanks for fast answers!

**Comment by arturmamedov** [comment]
SOLVED!

not use ```app('view.finder')```, that are different from:

```view()``` or  ```app()->make('view')``` or ```app('view')```
```php
Factory {#181 ▼
  #engines: EngineResolver {#176 ▶}
  #finder: FileViewFinder {#180 ▼
    #files: Filesystem {#149}
    #paths: array:2 [▼
      0 => "D:\serverpath\B04-Aprile2016\PaluSoft\www\laravel\resources\views"
      1 => "D:\serverpath\B04-Aprile2016\PaluSoft\www\laravel\Themes\AdminLTE/views/"
    ]
    #views: []
    #hints: array:14 [▶]
    #extensions: array:2 [▶]
  }
```
that have the my two paths and i can search and check for my Theme files to!

My solution:
```php
view()->exists('backend.user.role.index')
```

**Comment by kirkbushell** [comment]
Good to know - thanks for updating the issue @arturmamedov ! :)
