### ISSUE TITLE
Stylist::registerPath() should not be called statically

### ISSUE THREAD

**Issue by JeyKeu** [floatingpointsoftware/stylist#31]
I'm following the instructions from Readme. When I add

to the `register` method of my `AppServiceProvider` like so
`Stylist::registerPath('/resources/theme', true);`

I then added the `use` statement like so:
`use FloatingPoint\Stylist\Theme\Stylist;`

when i run `artisan` command I get this error:

`[ErrorException]                                                                                       
  Non-static method FloatingPoint\Stylist\Theme\Stylist::registerPath() should not be called statically `

I'm using Laravel 5.2.35 which is current as I submit this issue.

**Comment by joshbrw** [comment]
You're using the wrong class. You need to use the Facade - https://github.com/floatingpointsoftware/stylist/blob/master/src/Stylist/Facades/StylistFacade.php

**Comment by kirkbushell** [comment]
See comment by @joshbrw
