### ISSUE TITLE
Where i can find the documentation of all methods for `Theme::`?

### ISSUE THREAD

**Issue by arturmamedov** [floatingpointsoftware/stylist#33]
There are a documentation of all helpers methods? Thanks!

**Comment by kirkbushell** [comment]
@arturmamedov sorry what do you mean? Is there something in particular you're after?

**Comment by arturmamedov** [comment]
I mean methods for genearate script tag, or css <link...> tag, or get a path or url to theme assets etc. The only doc is the readme.md?

**Comment by kirkbushell** [comment]
Right, okay. Will note it down to add in future.

For now, this is the class you want to look at: 

https://github.com/floatingpointsoftware/stylist/blob/master/src/Stylist/Html/ThemeHtmlBuilder.php
