### ISSUE TITLE
Laravel 5.8 not work

### ISSUE THREAD

**Issue by rcngo** [floatingpointsoftware/stylist#44]
## Error 
```
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined method Illuminate\Events\Dispatcher::fire()
```

## Description

The **fire()** method is an alias to the **dispatch()** method. In laravel 5.8 the **fire()** method has been removed.

See: [[5.8] Remove `fire` method](https://github.com/laravel/framework/pull/26392/files )

**Comment by kirkbushell** [comment]
Thanks, @rcngo. I'll be spending some time very soon to upgrade to this to latest Laravel.
