### ISSUE TITLE
Theme has first letter uppercase, ::style, ::script looking for lower case

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#6]
Hello,

My theme folder has an first letter as upper case. 'Demo', 'Adminlte'.
But the `Theme::style()` method is looking for a `/themes/demo/` file.

**Comment by kirkbushell** [comment]
It should be getting published there. And I think that's a result of the URL helpers, not Stylist.

You should be using lowercase anyway. Do you think maybe the publishing should lowercase it? That would solve it I think.

**Comment by nWidart** [comment]
Hm, my bad, it correctly published to `public/demo`, all lowercase.
