### ISSUE TITLE
Theme not registered

### ISSUE THREAD

**Issue by nWidart** [floatingpointsoftware/stylist#8]
Hello,

I've got the following error: `Theme [Flatly] is not registered with Stylist.`

But when I dumb the theme paths, it's in there L101 https://cloudup.com/cJjtoyggpeB

Did I miss something ?

Thanks,

**Comment by kirkbushell** [comment]
Can you post your theme.json for that theme? It goes by the theme name, not the directory it sits in.

**Comment by nWidart** [comment]
That was the issue indeed! :blush: 
Renamed Demo-theme to Flatly-theme and forgot to change the `theme.json` file! 

Sorry :)

**Comment by kirkbushell** [comment]
No problem :)
